[0m21:24:59.820774 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c61310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fd8b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10495e130>]}


============================== 21:24:59.823228 | 23e7a038-5e2a-4fd0-ab04-ebe580add69c ==============================
[0m21:24:59.823228 [info ] [MainThread]: Running with dbt=1.5.4
[0m21:24:59.823537 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/stephenyang/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m21:24:59.823822 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stephenyang/Documents/spotify_astro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:24:59.824162 [debug] [MainThread]: Command `dbt run` failed at 21:24:59.824101 after 0.02 seconds
[0m21:24:59.824316 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c61310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fd8a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10495e130>]}
[0m21:24:59.824475 [debug] [MainThread]: Flushing usage events
[0m21:53:37.586287 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1065640d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ac4a00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107af8460>]}


============================== 21:53:37.589981 | 92c5fcee-c196-4462-9ab4-fec8613ad3c8 ==============================
[0m21:53:37.589981 [info ] [MainThread]: Running with dbt=1.5.4
[0m21:53:37.590285 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/stephenyang/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m21:53:37.590576 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stephenyang/Documents/spotify_astro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:53:37.590903 [debug] [MainThread]: Command `dbt test` failed at 21:53:37.590840 after 0.02 seconds
[0m21:53:37.591056 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1065640d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ac4a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b15be0>]}
[0m21:53:37.591217 [debug] [MainThread]: Flushing usage events
[0m13:05:26.059981 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075645b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b8d070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c08e20>]}


============================== 13:05:26.062575 | 899ab8ee-7e34-408d-a276-da8d3730c859 ==============================
[0m13:05:26.062575 [info ] [MainThread]: Running with dbt=1.5.4
[0m13:05:26.062901 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/stephenyang/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:05:26.063202 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stephenyang/Documents/spotify_astro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:05:26.063546 [debug] [MainThread]: Command `dbt test` failed at 13:05:26.063481 after 0.02 seconds
[0m13:05:26.063717 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075645b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b8d070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c08e20>]}
[0m13:05:26.063866 [debug] [MainThread]: Flushing usage events
[0m18:34:09.924335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b0dcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060c0c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060fc550>]}


============================== 18:34:09.928225 | 098b46b0-5410-48a1-90e7-bc6145dfcf31 ==============================
[0m18:34:09.928225 [info ] [MainThread]: Running with dbt=1.5.4
[0m18:34:09.928547 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/stephenyang/Documents/spotify_astro', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m18:34:09.928831 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stephenyang/Documents/spotify_astro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:34:09.929184 [debug] [MainThread]: Command `dbt run` failed at 18:34:09.929116 after 0.02 seconds
[0m18:34:09.929338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b0dcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060fccd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060fcc40>]}
[0m18:34:09.929498 [debug] [MainThread]: Flushing usage events
[0m09:38:12.860885 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10318cfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105558760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105562e50>]}


============================== 09:38:12.863945 | 12609278-575f-4c33-8db8-d298c706cd3b ==============================
[0m09:38:12.863945 [info ] [MainThread]: Running with dbt=1.7.8
[0m09:38:12.864251 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/stephenyang/Documents/GitHub/spotify_astro', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models browse_categories_flatten', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:38:12.864574 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/stephenyang/Documents/GitHub/spotify_astro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:38:12.875899 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.056145042, "process_user_time": 1.160089, "process_kernel_time": 0.215379, "process_mem_max_rss": "106921984", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m09:38:12.876203 [debug] [MainThread]: Command `dbt run` failed at 09:38:12.876130 after 0.06 seconds
[0m09:38:12.876385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10318cfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105522520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105533610>]}
[0m09:38:12.876569 [debug] [MainThread]: Flushing usage events
